name: ROS 1 Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:focal
    steps:
      - name: Setup ROS
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: noetic
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path : src
          submodules: recursive
      - name: clean ros2 workspace
        run:  rm -r src/mandeye_to_rosbag2
      - name: vcs 
        run: cd src && vcs import --input mandeye_to_rosbag1/livox.repos
      - name: rosdep
        run: . /opt/ros/noetic/setup.sh && rosdep update && rosdep install --from-paths src --ignore-src -r -y
      - name: Catkin build
        run: . /opt/ros/noetic/setup.sh && catkin_make
      